/-
Copyright (c) 2026 Wayne Brassem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Wayne Brassem
-/

import Mathlib

/-!

# Division Words and the Fully Accelerated Collatz Map

This module develops the dynamical and symbolic foundations used throughout
the formalization of finite fully accelerated Collatz trajectories.

The ordinary Collatz map is

    x ↦ x / 2          if x is even,
    x ↦ 3 * x + 1      if x is odd.

For a natural number `x`, define its division count by

    division_count x = v₂(3 * x + 1),

and define the fully accelerated map by

    fully_accelerated x
      = (3 * x + 1) / 2 ^ (division_count x).

The development separates naturally into four layers.

## 1. Ordinary and fully accelerated Collatz dynamics

The first layer establishes the arithmetic meaning of the accelerated map.

Every nonzero natural number may be written uniquely in the form

    n = 2^k * m

with `m` odd, where `k = v₂(n)`. The lemmas
`valuation_exponent_of_odd_factor` and `odd_part_of_padicValNat` formalize
the two facts needed here:

* the exponent of the maximal power of `2` is exactly the `2`-adic valuation;
* removing that power of `2` leaves an odd quotient.

Consequently,

    fully_accelerated x

is odd for every natural number `x`, while an odd input has a strictly
positive division count.

The module also relates the accelerated map directly to the ordinary
Collatz map. Starting from `2^k * y`, the first `k` ordinary Collatz steps
are halvings and leave `y`. Hence, for odd `x`,

    (collatz_step^[division_count x + 1]) x
      = fully_accelerated x.

Thus one fully accelerated iteration is exactly one ordinary odd Collatz
step followed by all halvings prescribed by the `2`-adic valuation of
`3 * x + 1`.

## 2. Division words generated by trajectories

A `division_word` is a finite list of natural numbers intended to encode
successive division counts.

For a starting value `x` and length `m`,

    division_counts x m

records the first `m` division counts generated along the fully accelerated
trajectory beginning at `x`.

The generated word has length exactly `m`. If the initial value is odd,
then every entry of the generated word is positive, since the first state
is odd and every subsequent fully accelerated iterate is odd.

This provides the symbolic encoding of finite accelerated trajectories used
by all later modules.

## 3. Validity, admissibility, and realization

The module distinguishes three increasingly dynamical notions.

A division word is **valid** when it is nonempty.

A division word is **admissible** when it is valid and every entry is at
least `1`.

A natural number `x` **realizes** a word `ω` when

    ω = division_counts x ω.length.

Thus admissibility is an intrinsic property of a symbolic word, whereas
realization asserts that the word is actually generated by a Collatz
trajectory.

Every nonempty division-count word generated from an odd starting value is
admissible. No converse is asserted in this module: the arithmetic
characterization of realizable words is developed later.

## 4. Word Length and Total Division Count

The total division count of a word is

    total_division_count ω = ω.sum.

For a word whose entries are all positive,

    ω.length ≤ ω.sum,

and therefore every admissible division word satisfies

    ω.length ≤ total_division_count ω.

This elementary inequality becomes important later when word length and
dyadic depth are compared.

## Dependency flow

The main logical dependencies are:

    ordinary Collatz dynamics
              │
              ▼
        `collatz_step`
              │
              │
              ├──────────────► `collatz_step_iterate_two_pow`
              │
              ▼
       `division_count`
              │
              ├── `valuation_exponent_of_odd_factor`
              │
              └── `odd_part_of_padicValNat`
              │
              ▼
      `fully_accelerated`
              │
              ├── `collatz_step_iterate_eq_fully_accelerated`
              │
              ├── `fully_accelerated_odd`
              │
              └── `division_count_pos`
              │
              ▼
       `division_counts`
              │
              ├── `division_counts_length`
              ├── `division_counts_pos`
              └── `division_counts_admissible`
              │
              ▼
    ┌──────────────────────────────────────────────┐
    │          Symbolic division words             │
    │                                              │
    │  `division_word`                             │
    │       ├── `valid_division_word`              │
    │       ├── `admissible_division_word`         │
    │       └── `realizes`                         │
    └──────────────────────────────────────────────┘
              │
              ▼
    ┌──────────────────────────────────────────────┐
    │          Total division count                │
    │                                              │
    │  `total_division_count`                      │
    │       ↓                                      │
    │  `division_word_length_le_sum_of_pos`        │
    │       ↓                                      │
    │  `division_word_length_le_total`             │
    └──────────────────────────────────────────────┘

These definitions and elementary dynamical facts form the symbolic
foundation for `Collatz.Affine`, where a division word is interpreted as a
formal composition of accelerated Collatz steps and represented by a single
affine transformation.

-/

namespace Collatz

/-! ## Ordinary and Fully Accelerated Collatz Dynamics -/

/--
The ordinary Collatz map on natural numbers.

Even inputs are halved; odd inputs are mapped to `3 * x + 1`.
-/
def collatz_step (x : ℕ) : ℕ :=
  if x % 2 = 0 then x / 2 else 3 * x + 1

/--
The `2`-adic division count associated with `x`.

It is the exponent of the highest power of `2` dividing `3 * x + 1`.
-/
def division_count (x : ℕ) : ℕ :=
  padicValNat 2 (3 * x + 1)

/--
If `n = 2^k * m` with `m` odd and `n ≠ 0`, then the `2`-adic
valuation of `n` is exactly `k`.

Equivalently, an odd cofactor contains no additional factor of `2`.
-/
lemma valuation_exponent_of_odd_factor
    {n k m : ℕ}
    (hn : n = 2 ^ k * m)
    (hm : Odd m)
    (hn0 : n ≠ 0) :
    padicValNat 2 n = k := by
  have hdiv : 2 ^ k ∣ n := by
    rw [hn]
    exact dvd_mul_right (2 ^ k) m
  have h_lower : k ≤ padicValNat 2 n := by
    exact
      (padicValNat_dvd_iff_le
        (p := 2) (a := n) (n := k) hn0).mp hdiv
  /-
  If the valuation were larger than `k`, then `2^(k+1)` would divide
  `n = 2^k * m`. Cancelling the common factor `2^k` would force
  `2 ∣ m`, contradicting the oddness of `m`.
  -/
  have h_upper : padicValNat 2 n ≤ k := by
    by_contra h
    have hval : k + 1 ≤ padicValNat 2 n := by
      omega
    have hpow : (2 : ℕ) ^ (k + 1) ∣ n := by
      exact
        (padicValNat_dvd_iff_le
          (p := 2) (a := n) (n := k + 1) hn0).mpr hval
    have hpow' : (2 : ℕ) ^ (k + 1) ∣ 2 ^ k * m := by
      rw [hn] at hpow
      exact hpow
    rw [pow_succ] at hpow'
    have htwo : (2 : ℕ) ∣ m := by
      exact Nat.dvd_of_mul_dvd_mul_left (by positivity) hpow'
    have hodd : ¬ (2 : ℕ) ∣ m := by
      rintro ⟨j, hj⟩
      rcases hm with ⟨r, hr⟩
      omega
    exact hodd htwo
  exact Nat.le_antisymm h_upper h_lower

/--
For nonzero `n`, removing its full `2`-adic factor leaves an odd number.

Writing `n = 2^k * m` with `m` odd,
`valuation_exponent_of_odd_factor` identifies `k` with
`padicValNat 2 n`, so division by `2^k` leaves the odd factor `m`.
-/
lemma odd_part_of_padicValNat
    {n : ℕ} (hn0 : n ≠ 0) :
    Odd (n / 2 ^ padicValNat 2 n) := by
  /-
  Decompose `n` into its power-of-two part and odd part, then identify
  the exponent with the `2`-adic valuation.
  -/
  obtain ⟨k, m, hm, hn⟩ :=
    Nat.exists_eq_two_pow_mul_odd hn0
  have hval : padicValNat 2 n = k :=
    valuation_exponent_of_odd_factor hn hm hn0
  rw [hval, hn]
  norm_num
  exact hm

/--
The fully accelerated Collatz map.

For odd `x`, this performs the ordinary Collatz step `3 * x + 1`
and then removes its entire power-of-two factor, equivalently applying
`division_count x` successive halvings.

The function is defined on all natural numbers. Its equivalence with
the corresponding finite sequence of ordinary Collatz steps is proved
below for odd starting values.
-/
def fully_accelerated (x : ℕ) : ℕ :=
  (3 * x + 1) / 2 ^ (division_count x)

/--
Starting from `2 ^ k * y`, the first `k` ordinary Collatz iterations
are successive halvings and therefore remove the entire factor `2 ^ k`,
leaving `y`.
-/
lemma collatz_step_iterate_two_pow
    (k y : ℕ) :
    (collatz_step^[k]) (2 ^ k * y) = y := by
  induction k with
  | zero =>
      simp only [pow_zero, one_mul, Function.iterate_zero_apply]
  | succ k ih =>
      /- One ordinary Collatz step removes the leading factor `2`. -/
      have hstep :
          collatz_step (2 ^ (k + 1) * y) = 2 ^ k * y := by
        have hfactor :
            2 ^ (k + 1) * y = 2 * (2 ^ k * y) := by
          rw [pow_succ]
          ring
        rw [hfactor]
        simp only [collatz_step, Nat.mul_mod_right, ↓reduceIte]
        exact Nat.mul_div_cancel_left _ (by norm_num)
      rw [Function.iterate_succ_apply, hstep]
      exact ih

/--
For odd `x`, one fully accelerated Collatz iteration is exactly one
ordinary odd Collatz step followed by the `division_count x` halvings
that remove the full power of `2` from `3 * x + 1`.
-/
theorem collatz_step_iterate_eq_fully_accelerated
    (x : ℕ)
    (hx : Odd x) :
    (collatz_step^[division_count x + 1]) x =
      fully_accelerated x := by
  have hmod : x % 2 = 1 := by
    obtain ⟨k, hk⟩ := hx
    omega
  have hfirst : collatz_step x = 3 * x + 1 := by
    simp [collatz_step, hmod]
  have hn0 : 3 * x + 1 ≠ 0 := by
    omega
  /-
  The full power of `2` determined by `division_count x` divides
  `3 * x + 1`.
  -/
  have hdiv : 2 ^ division_count x ∣ 3 * x + 1 := by
    apply (padicValNat_dvd_iff_le
      (p := 2)
      (a := 3 * x + 1)
      (n := division_count x)
      hn0).mpr
    simp only [division_count, le_refl]
  /-
  Factor `3 * x + 1` into its full power-of-two part and the
  resulting fully accelerated iterate.
  -/
  have hfactor :
      3 * x + 1 =
        2 ^ division_count x * fully_accelerated x := by
    unfold fully_accelerated
    calc
      3 * x + 1 =
          (3 * x + 1) / 2 ^ division_count x *
            2 ^ division_count x :=
        (Nat.div_mul_cancel hdiv).symm
      _ = 2 ^ division_count x *
            ((3 * x + 1) / 2 ^ division_count x) := by
        ac_rfl
  /-
  After the initial odd step, the remaining iterations are exactly
  the halvings handled by `collatz_step_iterate_two_pow`.
  -/
  calc
    (collatz_step^[division_count x + 1]) x
        = (collatz_step^[division_count x])
            (collatz_step x) := by
              rw [Function.iterate_succ_apply]
    _ = (collatz_step^[division_count x]) (3 * x + 1) := by
          rw [hfirst]
    _ = (collatz_step^[division_count x])
          (2 ^ division_count x * fully_accelerated x) := by
            rw [hfactor]
    _ = fully_accelerated x :=
          collatz_step_iterate_two_pow
            (division_count x) (fully_accelerated x)

/--
The fully accelerated Collatz map always produces an odd natural number.

The map removes the complete `2`-adic factor from `3 * x + 1`, so the
remaining quotient is its odd part. In particular, after one accelerated
step every subsequent state lies in the odd natural numbers.
-/
lemma fully_accelerated_odd (x : ℕ) :
    Odd (fully_accelerated x) := by
  unfold fully_accelerated
  unfold division_count
  exact odd_part_of_padicValNat (by omega)

/--
An odd natural number has a positive division count.

If `x` is odd, then `3 * x + 1` is even, so it is divisible by `2`.
Therefore its `2`-adic valuation, and hence `division_count x`, is at
least `1`.
-/
lemma division_count_pos
    (x : ℕ) (hx : Odd x) :
    1 ≤ division_count x := by
  unfold division_count
  have heven : Even (3 * x + 1) := by
    have h3x : Odd (3 * x) := by
      norm_num [Nat.odd_mul, hx]
    exact h3x.add_odd odd_one
  have hdiv : (2 : ℕ) ∣ 3 * x + 1 := by
    exact Even.two_dvd heven
  exact
    (padicValNat_dvd_iff_le
      (p := 2) (a := 3 * x + 1) (n := 1) (by norm_num)).mp hdiv

/-! ## Division Words Generated by Trajectories -/

/--
A division word is a finite sequence of natural numbers encoding
successive division counts in the fully accelerated Collatz dynamics.
-/
abbrev division_word := List ℕ

/--
The division word formed by the first `m` division counts along the
fully accelerated Collatz trajectory beginning at `x`.
-/
def division_counts (x m : ℕ) : division_word :=
  (List.iterate fully_accelerated x m).map division_count

/--
Every division count generated from an odd starting value is positive.

The initial division count is positive by `division_count_pos`, and every
subsequent accelerated state is odd by `fully_accelerated_odd`, so the same
argument applies inductively along the trajectory.
-/
lemma division_counts_pos
    (x m : ℕ)
    (hx : Odd x) :
    ∀ d ∈ division_counts x m, 1 ≤ d := by
  induction m generalizing x with
  | zero =>
      simp [division_counts]
  | succ m ih =>
      intro d hd
      simp only [division_counts, List.iterate] at hd
      rcases hd with hhead | htail
      · exact division_count_pos x hx
      · rename_i htail
        apply ih
            (fully_accelerated x)
            (fully_accelerated_odd x)
            d
        change d ∈ List.map division_count
          (List.iterate fully_accelerated (fully_accelerated x) m)
        exact htail

/-! ## Validity, Admissibility, and Realization -/

/-- A division word is valid exactly when it is nonempty. -/
def valid_division_word (ω : division_word) : Prop :=
  0 < ω.length

/--
A division word is admissible exactly when it is nonempty and every
division count is positive.
-/
def admissible_division_word (ω : division_word) : Prop :=
  valid_division_word ω ∧ ∀ d ∈ ω, 1 ≤ d

/--
Every nonempty finite division-count trace generated from an odd starting
value is an admissible division word.
-/
lemma division_counts_admissible
    (x m : ℕ)
    (hx : Odd x)
    (hm : 0 < m) :
    admissible_division_word (division_counts x m) := by
  unfold admissible_division_word
  constructor
  · simpa [valid_division_word, division_counts] using hm
  · exact division_counts_pos x m hx

/--
A natural number `x` realizes the division word `ω` when `ω` is exactly
the sequence of division counts along the first `ω.length` states of the
fully accelerated trajectory beginning at `x`.
-/
def realizes (x : ℕ) (ω : division_word) : Prop :=
  ω = division_counts x ω.length

/-! ## Word Length and Total Division Count -/

/-- The total division count of a division word is the sum of its entries. -/
def total_division_count (ω : division_word) : ℕ :=
  ω.sum

/-- The generated division-count word has length exactly `m`. -/
lemma division_counts_length (x m : ℕ) :
    (division_counts x m).length = m := by
  simp [division_counts]

/--
If every entry of a division word is positive, then the word's length
is at most the sum of its entries.
-/
lemma division_word_length_le_sum_of_pos
    (ω : division_word)
    (hpos : ∀ d ∈ ω, 1 ≤ d) :
    ω.length ≤ ω.sum := by
  /-
  Generalize the positivity hypothesis before induction so that the
  induction hypothesis applies to the tail with its restricted hypothesis.
  -/
  revert hpos
  induction ω with
  | nil =>
      intro hpos
      simp
  | cons d ω ih =>
      intro hpos
      have hd : 1 ≤ d := by
        exact hpos d (by simp)
      have htail : ∀ e ∈ ω, 1 ≤ e := by
        intro e he
        exact hpos e (by simp [he])
      have ih' : ω.length ≤ ω.sum := by
        exact ih htail
      /- Combine positivity of the head with the induction bound for the tail. -/
      calc
        (d :: ω).length = ω.length + 1 := by simp
        _ ≤ ω.sum + d := Nat.add_le_add ih' hd
        _ = d + ω.sum := by
          exact Nat.add_comm _ _
        _ = (d :: ω).sum := by simp

/--
The length of an admissible division word is at most its total
division count.
-/
lemma division_word_length_le_total
    {ω : division_word}
    (hω : admissible_division_word ω) :
    ω.length ≤ total_division_count ω := by
  /- Admissibility supplies nonemptiness and positivity; only positivity is needed here. -/
  rcases hω with ⟨_, hpos⟩
  unfold total_division_count
  exact division_word_length_le_sum_of_pos ω hpos

end Collatz
