/-
Copyright (c) 2026 Wayne Brassem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Wayne Brassem
-/

import Collatz.DivisionWords
import Collatz.Affine
import Collatz.Realizability
import Collatz.Cylinders
import Collatz.AffineContraction
import Collatz.ResidualForest
import Collatz.ResidualMass
import Collatz.DescentDensity

/-!

# Collatz

This is the root module for the formal Lean development of eventual descent
for the Collatz map through finite division words of the fully accelerated
dynamics.

The proof development is organized into eight modules.

## 1. Division Words

`Collatz.DivisionWords` defines the ordinary and fully accelerated Collatz
maps, division counts, finite division words, admissibility, realization, and
the basic structural properties of words generated by accelerated trajectories.

## 2. Affine Representation

`Collatz.Affine` develops the exact symbolic affine representation associated
with a division word. It proves the closed affine form, concatenation and
prefix identities, the explicit affine constant, the dyadic threshold
structure, and strict separation of the affine slope from one for nonempty
words.

## 3. Exact Realizability

`Collatz.Realizability` characterizes realization by an exact congruence
modulo `2^(D(ω)+1)`. It proves existence and uniqueness of the canonical
realization residue of every admissible word and develops residue refinement,
prefix lifting, realizability, and the nested-or-disjoint structure of exact
realization classes.

## 4. Dyadic Cylinders

`Collatz.Cylinders` interprets residue classes as dyadic cylinders. It develops
their generic nesting and binary refinement geometry, proves their finite
counting formulas and ordinary natural densities, defines realization
cylinders, and identifies symbolic prefix order with reverse cylinder
containment. Prefix-incomparable realization cylinders are therefore
disjoint.

## 5. Affine Contraction and Descent

`Collatz.AffineContraction` connects the dyadic threshold with contraction of
the affine branch. It establishes exact criteria for expansive and contractive
slopes, proves the rational pointwise descent threshold for a contractive
affine branch, and shows that sufficiently large realized points in a
contractive realization cylinder descend below their starting value.

## 6. The Residual Forest

`Collatz.ResidualForest` organizes admissible words that remain below the
contraction threshold into a residual prefix forest. It defines residual and
first-contraction words, proves finiteness of each residual level, constructs
the corresponding residual realization sets and exit layers, establishes
finite first passage, and defines the infinite residual set. In particular,
the initial residual population decomposes set-theoretically into finite-depth
first-contraction exits together with the infinite residual set.

## 7. Residual-Mass Decay

`Collatz.ResidualMass` assigns quantitative mass to the finite residual
populations. A weighted symbolic mass satisfies a uniform one-step
contraction, which yields a dyadic residual-mass envelope. A five-step bound
for the dyadic threshold gives a strict geometric contraction of that
envelope, and hence

    residual_mass m → 0.

The argument concerns the densities of finite-depth residual populations and
does not require continuity from above for the infinite residual intersection.

## 8. Density-One Eventual Descent

`Collatz.DescentDensity` converts the residual-mass estimate into the final
density theorem. Each fixed first-contraction layer has only finitely many
non-descending exceptions. Finite-depth first-passage covers then bound the
non-descending population by a fixed finite error together with a residual
population whose density can be made arbitrarily small.

The accelerated descent result is finally transferred back to the ordinary
Collatz map, yielding

    Collatz.ordinary_collatz_descent_has_natural_density_one.

Thus the set of positive integers whose ordinary Collatz trajectory eventually
falls below its starting value has natural density one.

This is a finite-stopping result. It does not assert that every Collatz
trajectory reaches `1`, nor does it exclude a sparse exceptional set of
starting values that never descend below their initial value.

## Proof Spine

The principal dependency flow is

    DivisionWords
        ↓
    Affine
        ↓
    Realizability
        ↓
    Cylinders
        ↓
    AffineContraction
        ↓
    ResidualForest
        ↓
    ResidualMass
        ↓
    DescentDensity

This root module introduces no additional mathematical definitions or
theorems. Importing `Collatz` exposes the complete verified proof spine.

-/
